// Mocks generated by Mockito 5.4.6 from annotations
// in canteen_mangement/test/features/auth/domain/usecases/delete_account_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:canteen_mangement/features/auth/domain/entities/auth_result_entity.dart'
    as _i2;
import 'package:canteen_mangement/features/auth/domain/entities/user_entity.dart'
    as _i3;
import 'package:canteen_mangement/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResultEntity_0 extends _i1.SmartFake
    implements _i2.AuthResultEntity {
  _FakeAuthResultEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthResultEntity> login(String? phone, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [phone, password]),
            returnValue: _i5.Future<_i2.AuthResultEntity>.value(
              _FakeAuthResultEntity_0(
                this,
                Invocation.method(#login, [phone, password]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResultEntity>);

  @override
  _i5.Future<_i2.AuthResultEntity> register(
    String? name,
    String? phone,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, phone, password]),
            returnValue: _i5.Future<_i2.AuthResultEntity>.value(
              _FakeAuthResultEntity_0(
                this,
                Invocation.method(#register, [name, phone, password]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResultEntity>);

  @override
  _i5.Future<_i3.UserEntity> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i5.Future<_i3.UserEntity>);

  @override
  _i5.Future<_i3.UserEntity> updateProfile({
    String? name,
    String? currentPassword,
    String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#updateProfile, [], {
                  #name: name,
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.UserEntity>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
